#!/bin/zsh

function g-quick () {
    echo -e "Running \e[34m./gradlew \e[32m--parallel -x checkstyleMain -x checkstyleTest -x test \e[35m--offline -s\e[0m"
    ./gradlew --parallel -x checkstyleMain -x checkstyleTest -x test --offline -s
}
