#!/usr/bin/env zsh

function helm-apply-config() {

	if [ -e "helm/images.yaml" ]; then
    	echo "moving to helm dir..."
    	cd helm
	fi
	echo -e "Running \e[34mhelmfile \e[32m-i apply\e[0m"
   	helmfile -i apply --context=3

}
